import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/providers/clientProvider";
import Navbar from "../components/navbar/navbar";
import { UserProvider } from "@/components/providers/userProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Sharvel",
	description: "Generated by create next app",
	// metadataBase: new URL('https://next-learn-dashboard.vercel.sh'),
	// keywords:,
	// viewport:,
	// robots:,
	// authors: "TYK",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<html lang="en">
			<body className="py-5 px-[150px]">
				<UserProvider>
					<ClientProvider>
						<Navbar />
						{children}
					</ClientProvider>
				</UserProvider>
			</body>
		</html>
	);
}
