import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/providers/clientProvider";
import Navbar from "../components/shared/Navbar";
import { UserProvider } from "@/providers/userProvider";
import Footer from "../components/footer/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Sharvel",
	description: "Generated by create next app",
	// metadataBase: new URL('https://next-learn-dashboard.vercel.sh'),
	// keywords:,
	// viewport:,
	// robots:,
	// authors: "TYK",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<html lang="en">
			<body className="">
				<UserProvider>
					<ClientProvider>
						<Navbar />
						<div className="py-[100px] px-[150px]">
							{children}
						</div>
						<Footer />
					</ClientProvider>
				</UserProvider>
			</body>
		</html>
	);
}
